id: d8bc22324a0a4c1b9d8e0fce455fda7a
initial_creation_type: ocr
source_metadata:
  volumes:
    968a514d3d844bbdadba0c8bfeadcb98:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: སེམས་ཀྱི་རྡོ་རྗེའི་བསྟོད་པ།
      total_pages: 1539
      volume_number: 1
